version: '3.8'
services:
  # Influx database
  influxdb:
    container_name: PFT-influxdb
    image: influxdb:latest
    ports:
      - '8086:8086'
    #  Persistent storage
    volumes:
      - influxdb-storage:/var/lib/influxdb
    env_file:
      - ${ENV_FILE}
  #  Grafana for data visualization
  grafana:
    container_name: PFT-grafana
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    # Persistent storage & importing Grafana config and provisioning
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    env_file:
      - ${ENV_FILE}

volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
